### ISSUE TITLE
it's asking for me to put in a pin, what pin?

### ISSUE THREAD

**Issue by miles5600** [akopachov/flipper-zero_authenticator-companion#12]

**Comment by akopachov** [comment]
It is asking you to input PIN in Authenticator app on Flipper device. That same PIN which you set when you ran Authenticator for the first time.

If you do not remember it - you may [reset Authenticator app](https://github.com/akopachov/flipper-zero_authenticator/wiki/How-to-reset-application%3F), that case all the settings (including all the tokens) will be reset to default and you will be able to set things up from scratch.
