### ISSUE TITLE
[FEATURE] Scan Google Authenticator Export Codes into Authenticator Companion

### ISSUE THREAD

**Issue by Ay1tsMe** [akopachov/flipper-zero_authenticator-companion#17]
**Is your feature request related to a problem? Please describe.**
The ability to import google authenticator QR codes into the authenticator companion. This would be nice as I don't know of a way to transfer my current Google authenticator tokens into the Flipper Zero.
**Describe the solution you'd like**
The QR code scanner having support for Google authenticator export codes.

**Comment by akopachov** [comment]
Great idea, thank you!

**Comment by akopachov** [comment]
Should be implemented in [v1.5.0](https://github.com/akopachov/flipper-zero_authenticator-companion/releases/tag/v1.5.0)
