### ISSUE TITLE
[FEATURE] Support for QR Code scanning in Wayland

### ISSUE THREAD

**Issue by Ay1tsMe** [akopachov/flipper-zero_authenticator-companion#26]
**Is your feature request related to a problem? Please describe.**
Add support for QR Code scanning in Wayland.

**Describe the solution you'd like**
Currently, QR Code scanning does not work in the Wayland compositor. It would be nice to be able to operate the QR code feature as this is the main function of the companion. QR codes are never detected on Wayland.

**Comment by akopachov** [comment]
The lib I'm using to take screenshots has following mentioned requirements:

On Linux, you need to install libxcb, libxrandr, and dbus.

Debian / Ubuntu:

apt-get install libxcb1 libxrandr2 libdbus-1-3
Alpine:

apk add libxcb libxrandr dbus

Mind trying them?

**Comment by Ay1tsMe** [comment]
Yes I have all them installed but still doesnt work. Im on an arch based distro if that helps?

**Comment by Ay1tsMe** [comment]
I had to use a Computer that had windows installed. The QR codes picked up just fine on Windows. I havnt tried other Linux distros but I'm assuming it's probably a Wayland problem rather than Linux. I'll try out QR code scanning on Ubuntu and get back to you

**Comment by akopachov** [comment]
Would you mind trying [v2.0.0](https://github.com/akopachov/flipper-zero_authenticator-companion/releases/tag/v2.0.0)?

In this release I got rid of custom library taking screenshots and replaced it with pure chromium + js approach.

**Comment by akopachov** [comment]
Mind trying [v2.0.1](https://github.com/akopachov/flipper-zero_authenticator-companion/releases/tag/v2.0.1)?

I got rid of usage 3rd party lib to take screenshots and migrated to pure chromium+js approach.

**Comment by Ay1tsMe** [comment]
I tried this version on wayland and it seems to get the screenshot correctly. When i pick QR on screen, it shows up with options to select my screen or specific windows and it displays the screenshot on of my screen on the Flipper Companion. However, when I click to scan for a QR code in the screenshot it is unable to find one.

**Comment by akopachov** [comment]
Thanks for checking.

When you picked a screen to take screenshot from, did you pick a screenshot of your entire screen or specific window? If not window - may you try picking screenshot of specific window which contain qr code?

**Comment by akopachov** [comment]
NVM.

If you have some time let's try [v2.0.2](https://github.com/akopachov/flipper-zero_authenticator-companion/releases/tag/v2.0.2)

I updated the screen capturing code there according to workarounds I found [here](https://github.com/electron/electron/issues/19177)

**Comment by akopachov** [comment]
Closing as there were no any activity here for a while.
