### ISSUE TITLE
Empty list when connecting for first time

### ISSUE THREAD

**Issue by yasbean** [akopachov/flipper-zero_authenticator-companion#32]
**Describe the bug**
I downloaded the Flipper Authentication Companion and opened it with F0 attached.  When opening the Authenticator on the F0, the FAC shows the List tab but it is empty.

**To Reproduce**
1. Attach F0 to computer
2. Open FAC
3. FAC shows "Waiting for Authenticator app top be launched on Flipper Zero device"
4. Open Authenticator Tool on F0
5. FAC changes to "Token list is empty"
6. Enter PIN on F0
7. No change on FAC

**Expected behavior**
I expected the list of keys on my F0 to be displayed

**Screenshots**

**Device information (please complete the following information):**
 - Firmware: Official stable
 - Firmware version 0.93

**Additional context**
Authenticator V5.5

**Comment by akopachov** [comment]
Could you try to execute CLI command `totp ls` manually? Highly-likely there is something off with it, given [this](https://github.com/akopachov/flipper-zero_authenticator/issues/211)

**Comment by yasbean** [comment]
I have installed, build, and installed totp.fap and it runs. The FAC list is still empty. If I open the CLI and execute `totp ls`, I receive the following error: `Failed to preload plugin. Code: 2`.

**Comment by akopachov** [comment]
Have you also extracted bunch of `.fal` files to `/ext/apps_data/totp/plugins`?

**Comment by yasbean** [comment]
No, I had not.  It all works, now. Thank you!

**Comment by akopachov** [comment]
Glad it is working for you now
