### ISSUE TITLE
[BUG] Typo in flipper-zero_authenticator-companion/src/routes/+layout.svelte code

### ISSUE THREAD

**Issue by L0sir1s** [akopachov/flipper-zero_authenticator-companion#37]
**Describe the bug**
The loading screen for the FAC shows "Waiting for Authenticator app top be launched on Flipper Zero device", when it should say "Waiting for Authenticator app to be launched on Flipper Zero device". 

**To Reproduce**
1. Launch Flipper Authenticator Companion

**Screenshots**
![image](https://github.com/akopachov/flipper-zero_authenticator-companion/assets/149820170/fb1a2e1a-f218-4e8d-a592-1a5131efdd74)

**Comment by akopachov** [comment]
Nice catch! Thanks!

Fixed in [latest release](https://github.com/akopachov/flipper-zero_authenticator-companion/releases/latest)
