### ISSUE TITLE
[BUG] Unnecessary timeout for fetching data

### ISSUE THREAD

**Issue by pxseu** [akopachov/flipper-zero_authenticator-companion#39]
**Describe the bug**
Having over 56 TOTP tokens causes a timeout error whilst fetching the data.

**To Reproduce**
1. Have a lot of accounts.
2. Open the app

**Expected behavior**
It should keep fetching while data is coming through, and not timeout without any reason.

**Device information (please complete the following information):**
 - Firmware: XTreme Dev
 - Firmware version: 46FBA200

**Additional context**

https://github.com/akopachov/flipper-zero_authenticator-companion/assets/57842793/e4cdebe5-95ad-43fa-916e-e07ce71a0181

**Comment by akopachov** [comment]
Should be fixed in [v2.9.3](https://github.com/akopachov/flipper-zero_authenticator-companion/releases/latest)
