### ISSUE TITLE
[FEATURE] - macOS Intel Build

### ISSUE THREAD

**Issue by tomck** [akopachov/flipper-zero_authenticator-companion#42]
**Is your feature request related to a problem? Please describe.**
Can't run program on Intel macs, which are still technically supported by Apple

**Describe the solution you'd like**
Add an x64 build target for macOS

**Describe alternatives you've considered**
I tried building it myself, I succeeded the first time but it complained about a missing 'conf' module, and then after that I was unable to successfully build again. because this command failed: `/usr/local/Cellar/node/22.5.1/bin/node /usr/local/Cellar/pnpm/9.7.0/libexec/lib/node_modules/pnpm/bin/pnpm.cjs rebuild @serialport/bindings-cpp@12.0.1`

**Additional context**
None needed

**Comment by akopachov** [comment]
Added MacOS x64 build target in [v2.9.7](https://github.com/akopachov/flipper-zero_authenticator-companion/releases/tag/v2.9.7).
Give it a try and let me know if any issues.

**Comment by tomck** [comment]
WFM, thanks
