### ISSUE TITLE
[BUG] Cant export keys from google Authentificator app Android

### ISSUE THREAD

**Issue by msazanov** [akopachov/flipper-zero_authenticator-companion#44]
**Describe the bug**
Emigration from Google Authenticator does not work. I tried it through a webcam, screenshot. And unfortunately it is not exported

If I use the camera, I get the error: QR code found but seems to be non-valid Google Authenticator migration QR code
Log:
› Error: Invalid import data URL
at Oe (app://-/_app/immutable/nodes/9.KtifrkkP.js:1:1716)
at g (app://-/_app/immutable/nodes/9.KtifrkkP.js:3:2983)
at xe.s (app://-/_app/immutable/nodes/9.KtifrkkP.js:3:2888)
at app://-/_app/immutable/chunks/scheduler.B20lkZws.js:1:7766
at Array.forEach (<anonymous>)
at app://-/_app/immutable/chunks/scheduler.B20lkZws.js:1:7752
at c.$$.dirty.g.returnDetailedScanResult [as _onDecode] (app://-/_app/immutable/chunks/screen-qr-scanner.B02xm1v4.js:3:20713)
at app://-/_app/immutable/chunks/screen-qr-scanner.B02xm1v4.js:3:14016

If i use screenshot, I get the another error
No valid QR code found
But no error in log

**To Reproduce**
1. Go to 'Import'
2. Select 'Google Authentificator'
3. Try to export

**Expected behavior**
I hoped that all the keys would appear

**Screenshots**
![image](https://github.com/user-attachments/assets/f3e15044-4559-4f9d-b8fa-a1bf08a104c6)
![image](https://github.com/user-attachments/assets/6504a5f2-ba84-47bd-af08-fa498088d852)

**Device information (please complete the following information):**
 - Firmware: unlshd-078e
 - OS Linux
 - Flipper-Authenticator-Companion-2.9.8.AppImage

**Comment by akopachov** [comment]
How many items do you have in Google Authenticator?

**Comment by akopachov** [comment]
Should be fixed in [v2.9.9](https://github.com/akopachov/flipper-zero_authenticator-companion/releases/latest)

**Comment by msazanov** [comment]
![image](https://github.com/user-attachments/assets/aa4ef761-93fe-4dc2-9586-3610e6b04cdf)
When trying to select a QR code from the screen, the error is the same. Also, the webcam has stopped working now, before that a window with a camera image appeared, now a line with the camera is simply displayed, but there is no image. I tried to scan the QR anyway, suddenly it's only a GUI problem, but scanning doesn't work either.
![image](https://github.com/user-attachments/assets/ba59cbee-8231-42cb-b268-4e22601c160b)

**Comment by msazanov** [comment]
i also have same problem with camera on OS Windows, but QR from screen reads correctly.
On linux i tried to use X11 and wayland, but no mater.

**Comment by akopachov** [comment]
Fixed issue with camera scanner. Just a regression after Svelte 5 upgrade.
I managed to successfully import the following QR codes I generated from test TOTP items: 

![photo_2024-10-30_09-37-06](https://github.com/user-attachments/assets/efd5f4d1-d3c5-4429-ad8e-79624600d992)
![photo_2024-10-29_20-46-13](https://github.com/user-attachments/assets/e47b26e0-65db-4880-ba7b-53e239ded601)

Tried via camera scanner and screen scanner on Windows 11. Could you please try [the latest release v.2.9.10](https://github.com/akopachov/flipper-zero_authenticator-companion/releases/latest) and let me know if it makes things better for you? Also, let me know if you can scan the two QR codes above.

> [!CAUTION]
> Please, don't share your QR code here.

**Comment by msazanov** [comment]
Sorry for long answer, all works good :) The only problem is the sliding of the watch, but this is a physical problem of the device, not this application.
